pipeline {
    agent {
        docker { 
            // Use a valid 2026 image tag
            image 'eclipse-temurin:21-jdk' 
        }
    }
    stages {
        stage('Build') {
            steps {
                // Dynamically create the file if it's not in your repo
                sh 'echo "public class HelloWorld { public static void main(String[] args) { System.out.println(\\\"Hello from a 2026 Docker Node!\\\"); } }" > HelloWorld.java'
                sh 'javac HelloWorld.java'
            }
        }
        stage('Execute') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}
