pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
           stage('Compile') {
            agent {
                docker {
                    image 'eclipse-temurin:21-jdk-alpine-3.23' args '--entrypoint ""'
                }
            }
            steps {
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            agent {
                docker {
                    image 'eclipse-temurin:21-jdk-alpine-3.23' args '--entrypoint ""'
                }
            }
            steps {
                sh 'java HelloWorld'
            }
        }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
