pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Compile') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
                // Compiles the Java file
                sh 'javac HelloWorld.java'
            }
        }
    stage('Execute') {
      agent {
        docker { image 'node:16-alpine' }
      }
        steps {
                // Runs the compiled class
                sh 'java HelloWorld'
            }
        }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
